version: "1"

volumes:
  db:

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "authmaster"
      POSTGRES_PASSWORD: "authmaster"
      POSTGRES_DB: "authmaster"
    volumes:
      - "db:/var/lib/postgresql/data"
    restart: always
  backend:
    image: "nemesisryg/authmaster:latest"
    environment:
      AUTHLIB_INSECURE_TRANSPORT: 1
      DB_URI: "postgresql://authmaster:authmaster@db/authmaster"
      PYTHONUNBUFFERED: 1
      RECOVERY_SECS: 300
      SECRET_KEY: "secret"
      SENDINBLUE_KEY: "???"
    ports:
      - "8000:80"
    depends_on:
      - db
    restart: always